-- Sample Code for Warehouse and Schema Creation
CREATE WAREHOUSE IF NOT EXISTS ml_wh
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS diabetes_db;

CREATE SCHEMA IF NOT EXISTS diabetes_db.public;

USE WAREHOUSE ml_wh;
USE DATABASE diabetes_db;
USE SCHEMA public;
